# Numpy

# Q1: Write a function so that the columns of the output matrix are powers of the input vector ( output column is the input vector raised element-wise to the power of N - i - 1)

In [1]:
import numpy as np


In [3]:
x = np.array([1,2,3,4])
n = 3

In [5]:
np.vander(x, n)

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [16,  4,  1]])

In [7]:
np.column_stack([x**(n-1-i) for i in range(n)])

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [16,  4,  1]], dtype=int32)

In [8]:
x = np.array([1, 2, 3, 5])
np.vander(x)

array([[  1,   1,   1,   1],
       [  8,   4,   2,   1],
       [ 27,   9,   3,   1],
       [125,  25,   5,   1]])